* se corrige la funcion de comprobacion de memoria * se cambia la ubicacion de la gestion de los archivos .pid

diff --git a/config/includes.chroot/usr/local/bin/destruir b/config/includes.chroot/usr/local/bin/destruir
--- a/config/includes.chroot/usr/local/bin/destruir
+++ b/config/includes.chroot/usr/local/bin/destruir
@@ -1,5 +1,9 @@
 #!/bin/bash
 # elaborado por sinfallas
+if [[ $USER != root ]]; then
+echo -e "\e[00;31mERROR: DEBES SER ROOT\e[00m"
+exit 1
+fi
 echo $BASHPID > /run/destruir.pid
 miswap=$(fdisk -l | grep swap | cut -c 1-9)
 miswap2=$(blkid -o export $miswap | grep UUID)
